name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask
    - name: Run tests
      run: |
        python -m unittest discover -s . -p "test_*.py"

    - name: Setup Google Cloud SDK # Setup Google Cloud SDK (skip if already installed in the environment)
      run: |
        if ! gcloud --version; then
          curl -sSL https://sdk.cloud.google.com | bash
        fi
      env:
        GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}

    # Authenticate with Google Cloud
    - name: Set up Google Cloud
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    # Configure Docker to use the gcloud command-line tool as a credential helper
    - name: Configure Docker
      run: gcloud auth configure-docker

    # Add Docker build if not already part of the workflow
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/lofty-root-docker-test/flask-app:latest

    # Deploy to Cloud Run
    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v0.7.0
      with:
        service: flask-app  # Name of your Cloud Run service
        image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-app:latest
        credentials: ${{ secrets.GCLOUD_SERVICE_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        region: us-central1  # Specify the region your Cloud Run service is in
