name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask

    - name: Run tests
      run: |
        python -m unittest discover -s . -p "test_*.py"

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

    - name: Build and Push Docker image to Google Artifact Registry
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/lofty-root-docker-test/flask-app:latest .
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/lofty-root-docker-test/flask-app:latest

    # Add Docker build if not already part of the workflow
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/lofty-root-docker-test/flask-app:latest

    # Deploy to Cloud Run
    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v0.7.0
      with:
        service: flask-app
        image: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/lofty-root-docker-test/flask-app:latest
        credentials: ${{ secrets.GCLOUD_SERVICE_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        region: us-central1  # Specify the region your Cloud Run service is in
